### ISSUE TITLE
Unexpected token =

### ISSUE THREAD

**Issue by ghost** [sunyuting83/blog-cfw-github#1]
[![B4GFk4.md.jpg](https://s1.ax1x.com/2020/11/07/B4GFk4.md.jpg)](https://imgchr.com/i/B4GFk4)

**Comment by ghost** [comment]
还有
worker.js的53行： }
worker.js的108行：      theRequest[strs[i].split("=")[0]]=unescape(strs[i].split("=")[1]);
怎么改呢

**Comment by sunyuting83** [comment]
> 还有
> worker.js的53行： }
> worker.js的108行： theRequest[strs[i].split("=")[0]]=unescape(strs[i].split("=")[1]);
> 怎么改呢

##### 不好意思，我太粗心了。说明写错了。
blog.js的53行修改成你的worker地址
```
const worker_url = 'https://blog.nds9.workers.dev'
```
这里改成你的worker地址

worker.js的171行修改成你的github帐号
> 这个是因为我改过一次代码，加了些内容。忘记改说明了。
```
const github = 'sunyuting83',
        repository = 'blog-cfw-github'
# repository是你的项目名称(如果你修改过)
```

### 截图的报错，有可能是node版本的问题。
我的环境版本：v12.18.3
可以尝试修改成：
```
function MakeMD5(str) {
  some code
}
```

### 一些说明
- 这个post.js不是最终版，很多功能还没做完 :( 暂时只有自动添加blog序号的功能(好像)。可以自动生成序号后手动修改: 编号.md的内容。
- 提交可以使用，但要设置好github的帐号
- blog的排序也有问题。现在不是倒序。
我会抽时间完善的。

**Comment by ghost** [comment]
谢了 解决了

**Comment by ghost** [comment]
如果给域名设了workers映射，blog地址可改为域名么

**Comment by ghost** [comment]
我在卸载系统自带nodejs（10.16.0）后使用了官网的14.15.0后恢复正常

**Comment by sunyuting83** [comment]
> 如果给域名设了workers映射，blog地址可改为域名么

1. 设置路由规则 
![设置路由规则](https://p.pstatp.com/origin/138a100007ad085fc810e "set router")
2. 添加DNS
![添加DNS](https://p.pstatp.com/origin/138570001bad9b77b0e3d "add a CNAME to DNS")

**Comment by ghost** [comment]
实测只要再增加2个route www.address.com/ www.address.com(www.address.com表示你的域名)
然后dns设置只要存在 不用cname到worker 随便填 127.0.0.1都行

**Comment by sunyuting83** [comment]
看来是cf的router优先级最高。

**Comment by gamecss** [comment]
话说卡loading怎么办啊

**Comment by gamecss** [comment]
worker代码就是我blog-cfw-github的

**Comment by gamecss** [comment]
就是没有页面，标题显示loading...(浏览器不在加载状态）

**Comment by gamecss** [comment]
访问/blog.js提示404

**Comment by gamecss** [comment]
把脚本第175行的master改main之后圈圈出来了，/blog.js也可以了，但还是无限转弯

**Comment by gamecss** [comment]
得，我解决了，是我手贱把每个raw.githubusercontent.com都加上了gamecss/blog-cfw-github/main，可以了

**Comment by ghost** [comment]
p.s. 催更
